# asdf vm
. "$HOME/.asdf/asdf.sh"
# append completions to fpath
fpath=(${ASDF_DIR}/completions $fpath)
# initialise completions with ZSH's compinit
autoload -Uz compinit && compinit

# JAVA
export JAVA_HOME=$(/usr/libexec/java_home)

# Dotnet
export PATH="$PATH:$HOME/.dotnet/tools"

# Golang
export GOPATH=$(go env GOPATH)
export PATH=$PATH:$(go env GOPATH)/bin

# Android
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools

# Flutter
export PATH=$PATH:$HOME/Project/Environment/flutter/bin

# remove duplicat entries from $PATH
# zsh uses $path array along with $PATH 
typeset -U PATH path
